name: Deploy to ACR and ACI

on:
  push:
    branches:
      - tp3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        dockerfile: Dockerfile
        imageName: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: devops-20211305
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1
        location: westeurope
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        name : 20211305

    - name: Logout of Azure Container Registry
      run: docker logout ${{ secrets.REGISTRY_LOGIN_SERVER }}