name: Build and publish Docker image

on:
  push:
    branches: [ tp2 ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Check Dockerfile syntax with Hadolint
      run: docker run --rm -i hadolint/hadolint < dockerfile
      continue-on-error: true

    - name: Build Docker image
      if: ${{ !failure() }}
      run: docker build -t stang94/tp2:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      if: ${{ !failure() }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: stang94/tp2:latest

