name: Deploy to ACR and ACI

on:
  push:
    branches:
      - tp3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Connexion à Azure Container Registry (ACR)
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build et push de l'image à ACR
    - name: Build and push image to ACR
      uses: azure/docker@v1
      with:
        context: .
        dockerfile: Dockerfile  # Assurez-vous d'avoir un fichier Dockerfile à la racine de votre projet
        imageName: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1

      # Déploiement de l'ACI à partir de l'ACR
    - name: Deploy to ACI
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: devops-20211305
        container-name: ${{ secrets.RESOURCE_GROUP }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1
        location: westeurope
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}

