name: Deploy to ACI

on:
  push:
    branches:
      - tp3  # Mettez ici la branche que vous souhaitez surveiller pour les déclenchements

env:
  RESOURCE_GROUP: ADDA84-CTP
  LOCATION: westeurope
  DNS_LABEL: devops-20211305
  CONTAINER_NAME: 20211305  # Remplacez par votre identifiant EFREI
  ACR_LOGIN_SERVER: efreiprediction.azurecr.io
  ACR_REPOSITORY: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1  # Assurez-vous de remplacer "efreiprediction" par votre ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v2

      # Connexion à Azure Container Registry (ACR)
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build et push de l'image à ACR
      - name: Build and push image to ACR
        uses: azure/docker@v1
        with:
          context: .
          dockerfile: Dockerfile  # Assurez-vous d'avoir un fichier Dockerfile à la racine de votre projet
          imageName: ${{ env.ACR_REPOSITORY }}

      # Déploiement de l'ACI à partir de l'ACR
      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          dns-name-label: ${{ env.DNS_LABEL }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.ACR_REPOSITORY }}
          location: ${{ env.LOCATION }}
          registry-login-server: ${{ env.ACR_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}

