name: Deploy to ACR and ACI

on:
  push:
    branches:
      - tp3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check dockerfile with hadolint
      run: |
        docker run --rm -i hadolint/hadolint < dockerfile
        if grep -q "warning" hadolint_output.txt; then
          echo "Hadolint found warnings in Dockerfile. Fix the warnings and try again."
          exit 1
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Preparing image
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - name : push and build docker image
      run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: devops-20211305
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211305:v1
        location: westeurope
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: 20211305
        ports: 8081
        secure-environment-variables: |
          API_KEY=${{ secrets.OPENWEATHER_API_KEY }}

